#!/usr/bin/env bash
set -e

# ERROS move these to dev startup
# cd lib/neuroglancer-chat/
# pip install -e .
# cd -

# cd lib/molmo-glancer/
# pip install -e .
# cd -

# command not found
# playwright install --with-deps chromium